f=open("text.txt",'r')
line1=f.readline()
print(line1,end=' ')
line2=f.readline()
print(line2,end=' ')
line3=f.readline()
print(line3,end=' ')
line4=f.readline()
print(line4,end=' ')
line5=f.readline()
print(line5,end=' ')
f.close()
